baseURL = 'https://blog.fnicen.top/'
title = "FICN's blog"
theme = 'PaperMod'
pagination.pagerSize = 5

[taxonomies]
tag = "tags"
category = "categories"

[params]
ShowCodeCopyButtons = true

[params.profileMode]
enabled = true
title = "FICN的博客"
subtitle = "欢迎"

[[params.profileMode.buttons]]
name = "最新"
url = "/posts"
[[params.profileMode.buttons]]
name = "分类"
url = "/categories"
[[params.profileMode.buttons]]
name = "归档"
url = "/archives"
[[params.profileMode.buttons]]
name = "关于"
url = "/about"

# [[params.socialIcons]]
# name = "bilibili"
# url = "https://space.bilibili.com/8579681"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/FnICeN"



